registration form mockup
BuildForSDG/PulaniFront pull request #14
Opened 2020-06-03 19:37 UTC by BryanCI

## Description
mock up of the registration form for users of the pulani app

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #3 

## How Has This Been Tested?
just a mock up

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-06-05 03:13 UTC, Mwamitovi commented
@BryanCI despite this being a mockup that we agreed needs to be kept within the project, kindly run `npm test` for our assurance that nothing is broken within the app.

2020-06-05 03:16 UTC, Mwamitovi requested changes
@BryanCI despite this being a mockup that we agreed needs to be kept within the project, kindly run `npm test` for our assurance that nothing is broken within the app.

**In fact, that's what the last checkbox within the checklist above requires.** 
Remember to attach a screenshot, and mark the last  box with checkbox with "x"

2020-06-05 10:30 UTC, Nataanthoni submitted a review, later dismissed

2020-06-07 16:03 UTC, halimahbukirwa approved these changes

2020-06-07 18:19 UTC, Mwamitovi approved these changes

2020-06-07 18:53 UTC, merged