product user data capture form mockup
BuildForSDG/PulaniFront pull request #15
Opened 2020-06-03 19:56 UTC by BryanCI

## Description
Product data entry form. this is a form to capture data form an entrepreneur in the category of product. this form capture data for a business person who provides product forexample making and selling chapatis. thats a product put on market

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #7 

## How Has This Been Tested?
its just a mockup

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-06-05 03:18 UTC, Mwamitovi requested changes
@BryanCI   despite this being a mockup that we agreed needs to be kept within the project, kindly run `npm test` for our assurance that nothing is broken within the app.

**In fact, that's what the last checkbox within the checklist above requires.** 
Remember to attach a screenshot, as evidence.

2020-06-05 03:40 UTC, Mwamitovi reviewed
Just as discussed, this is fine.

2020-06-07 16:00 UTC, Mwamitovi approved these changes
This looks ready to merge

2020-06-07 16:02 UTC, halimahbukirwa approved these changes

2020-06-07 18:56 UTC, Nataanthoni approved these changes

2020-06-07 18:56 UTC, merged