service form mockup
BuildForSDG/PulaniFront pull request #17
Opened 2020-06-04 17:46 UTC by halimahbukirwa

## Description
Service form mock-up

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #8 

## How Has This Been Tested?
No need of testing
## Screenshots (if applicable, else remove this line / section)
No need of testing

## Checklist:

2020-06-05 03:26 UTC, Mwamitovi requested changes
@halimahbukirwa  despite this being a mockup that we agreed needs to be kept within the project, kindly run `npm test` for our assurance that nothing is broken within the app.

**In fact, that's what the last checkbox within the checklist above required.** Please include those checkboxes, remember to attach a screenshot (of tests), and mark the last  box with "x"

2020-06-05 03:35 UTC, Mwamitovi requested changes
@halimahbukirwa, please do not capitalize the file names (leave them all as lowercase).
Otherwise, you'll have a lot of merge conflicts going forward.

Please change that...

2020-06-07 15:54 UTC, BryanCI approved these changes

2020-06-07 18:56 UTC, Nataanthoni approved these changes

2020-06-10 06:07 UTC, merged